### ISSUE TITLE
Plugin hangs on "Retrieving drive information"

### ISSUE THREAD

**Issue by 88lex** [cguZZman/drive-login#2]
When running the Google Add On in Kodi the plugin will hang after authentication using heroku has succeeded. 
The onscreen message is "Retrieving drive information", but the add on never continues from that popup.  Waited over an hour.

This occurred on both a Shield and a FireTV 4k (latest editions).
It was successful with some other devices including PC and Mac with Kodi.

I tried repeatedly:
- Clearing cache for Kodi.
- Uninstalling/reinstalling the add on.
- Clearing all data for Kodi.
- Rebooting the device.
- Running the auth with heroku on a different PC, on a phone and on the firetv/shield itself. Each time the auth was successful.
- Running the auth on other google accounts
- Uninstalling/reinstalling Kodi.
- Installing Kodi versions 17.6, 18.3 and 18.4 and using the add on with each of them.

As mentioned, the auth works with the google accounts I was using when it was run from a different device (PC and Mac). I did this after running the above diagnostics, so there was no 'preexisting auth' that might have conflicted with the firetv/shield auths.

Anything else you can think of to try? Is this a known issue?
Otherwise love the add on.

**Comment by cguZZman** [comment]
Please post your debug log file. https://kodi.wiki/view/Log_file/Easy
