### ISSUE TITLE
Showing error in Login 

### ISSUE THREAD

**Issue by Varun23102002** [cguZZman/drive-login#4]
Hello bro Google blocked your app access please create new app

**Comment by Noorani786630** [comment]
Same issue please fix it

![IMG_20240419_175109](https://github.com/cguZZman/drive-login/assets/157985225/fb75b83e-049c-40af-baf9-c68dd7bc076c)

**Comment by Varun23102002** [comment]
Please guys comment the alternative way to play Google drive video files in phone and Tv

**Comment by cguZZman** [comment]
Commented about this here: https://github.com/cguZZman/plugin.googledrive/issues/342#issuecomment-2068194082
